spring.application.name=Assignment1

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=26MB

openai.api.base-url=https://api.openai.com/v1
openai.api.model=gpt-4o-mini-transcribe
openai.api.key=${OPENAI_API_KEY:}
openai.api.connect-timeout=2s
openai.api.read-timeout=20s
